config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, only: [:new, :create]
    resources :reviews, only: [:new, :create]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses, dependent: :destroy
  has_many :reviews
  validates :name, uniqueness: true, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 3 }
  has_one_attached :image
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :quantity, presence: true, numerricality: true
  validates :unit, presence: true,
                   inclusion: { in: ['ml', 'cl', 'dl', 'gr', 'table spoon', 'coffee spoon', 'slice', 'piece'] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, lenght: { minimum: 3 }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :scrore, inclusion: { in: 0..5, allow_nil: false }
  validates :comment, presence: true, lenght: { minumum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: %i[new edit show destroy]

  def index
    @cocktails = params.include?(:query) ? Cocktail.where("lower(name) LIKE '%#{params[:query].downcase}%'") : Cocktail.all
  end

  def show; end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :description, :image)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>
<div class="container-cocktails">
  <% @cocktails.each do |cocktail| %>
    <%= link_to cocktail_path(cocktail) do %>
      <% if cocktail.image.attached? %>
        <div class="card" style="backround-image: url(<%= cl_image_tag cocktail.image.key, width: 300, height: 200, crop: :fill %>); ">
      <% else %>
        <div class="card">
      <% end %>
          <h3><%= cocktail.name %></h3>
        </div>
    <% end %>
      
  <% end %>
</div>

app/views/cocktails/show.html.erb
<h1>Cocktails#show</h1>
<p>Find me in app/views/cocktails/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mister Cocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
  </head>

  <body>
  <nav>
    <%= link_to cocktails_path do %>
      <span><i class="fas fa-home"></i> Mister cocktail</span>
    <% end %>

    <form action="/cocktails" method="GET" class="form-inline">
      <input type="text" name="query" id="query" class="form-inline-input">
      <input type="submit" value="Search" class="form-inline-submit">  
    </form>

    <a href="#"><i class="fas fa-plus-square"></i> Add cocktail</a>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>